name = "sdacrealtimedashboard"
main = "src/index.js"
compatibility_date = "2024-05-01"

[vars]
GOV_BTC_ADDRESSES = "bc1qgdjqv0sz9v770m9tc0u7jshm9e66n6wulvcl66,bc1qmxj8v6m5k56n6wulvcl66,3Kzh9qmc2V9ndpYJCfSUTv87Z56tM84r4a,bc1q5p9p9p9p9p9p9p9p9p9p9p9p9p9p9p9p9p9"
# Note: These include known Silk Road seizure and Bitfinex hack recovery wallets.

[[kv_namespaces]]
binding = "WATCHTOWER_KV"
id = "634ce5894e8a4f54a0688d8d3a839fbd"
preview_id = "634ce5894e8a4f54a0688d8d3a839fbd"

[triggers]
crons = ["*/5 * * * *"] # Every 5 minutes

[[d1_databases]]
binding = "DB"
database_name = "watchtower-db"
database_id = "79946b37-8cd0-4fb3-ad91-44fe81543d41"
